### PR TITLE
Make timeouts configurable on the client

### PR DESCRIPTION
**Pull request by pwaller**
This adds a configuration parameter to the `Client` and documents it in
the README.md.

### CODE REVIEW

**Comment by tristanojbacon** [comment]
Would it be beneficial to provide an example of how large a large document is? E.g., over X pages, or over Xmb?

**Comment by pwaller** [comment]
Good question. Unfortunately there isn't a trivial formula. A pathological 100 page document could be large. More typically, I would be expecting it to be a problem once you get up to 500-1000 pages. But there is no magic number or size that is necessarily a problem, since the time to convert individual pages can vary depending on things which are not related to either the size nor the number of pages.

**Comment by tristanojbacon** [comment]
Ok, that makes sense. Does a timeout produce an error at the moment, or does it just hang? If an error was provided, at least the user would know to look for a solution to a timeout in the Readme

**Comment by pwaller** [comment]
Looks like it's the following for the default timeout:
```
ReadTimeout: HTTPSConnectionPool(host='pdftables.com', port=443): Read timed out. (read timeout=300)
```

**Comment by pwaller** [comment]
@tristanojbacon, I just updated it:

screenshot from 2017-04-25 10-49-01

**Comment by duncanharris** [comment]
Presume we don't really need to cope with duff values such as None or negative numbers for the timeout or it not being a tuple.

**Comment by tristanojbacon** [comment]
Looks good to me @pwaller!

**Pull request merged**
